# Cloud Build Configuration for Cultural Bias Shield
# Builds and deploys the full-stack application to Google Cloud Platform

steps:
  # Build the backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/cultural-bias-shield-backend:$BUILD_ID'
      - '-f'
      - 'backend/Dockerfile'
      - './backend'

  # Push the backend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/cultural-bias-shield-backend:$BUILD_ID'

  # Build the frontend
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd frontend
        npm install
        npm run build

  # Build the frontend Docker image  
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/cultural-bias-shield-frontend:$BUILD_ID'
      - '-f'
      - 'frontend/Dockerfile'
      - './frontend'

  # Push the frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/cultural-bias-shield-frontend:$BUILD_ID'

  # Deploy backend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'cultural-bias-shield-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/cultural-bias-shield-backend:$BUILD_ID'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '100'
      - '--set-env-vars'
      - 'GEMINI_API_KEY=${_GEMINI_API_KEY},GOOGLE_CLOUD_PROJECT=$PROJECT_ID'

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'cultural-bias-shield-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/cultural-bias-shield-frontend:$BUILD_ID'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '50'

  # Apply Terraform infrastructure (if needed)
  - name: 'hashicorp/terraform:1.6'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd deployment/terraform
        terraform init
        terraform plan -var="project_id=$PROJECT_ID" -var="region=${_REGION}"
        terraform apply -auto-approve -var="project_id=$PROJECT_ID" -var="region=${_REGION}"

# Substitutions for flexible deployment
substitutions:
  _REGION: 'us-central1'
  _GEMINI_API_KEY: 'your-gemini-api-key-here'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  substitutionOption: 'ALLOW_LOOSE'

# Build timeout (30 minutes)
timeout: '1800s'

# Images to store in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/cultural-bias-shield-backend:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/cultural-bias-shield-frontend:$BUILD_ID'
